//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmorYPazBackend.ServicioUser {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", ConfigurationName="ServicioUser.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerIEDeUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerIEDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioResponse obtenerIEDeUsuario(AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerIEDeUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerIEDeUsuarioResponse")]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioResponse> obtenerIEDeUsuarioAsync(AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/verificarUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/verificarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AmorYPazBackend.ServicioUser.verificarUsuarioResponse verificarUsuario(AmorYPazBackend.ServicioUser.verificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/verificarUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/verificarUsuarioResponse")]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.verificarUsuarioResponse> verificarUsuarioAsync(AmorYPazBackend.ServicioUser.verificarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerTipoUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerTipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AmorYPazBackend.ServicioUser.obtenerTipoUsuarioResponse obtenerTipoUsuario(AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerTipoUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerTipoUsuarioResponse")]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerTipoUsuarioResponse> obtenerTipoUsuarioAsync(AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerUgelDeUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerUgelDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioResponse obtenerUgelDeUsuario(AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerUgelDeUsuarioRequest", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/UsuarioWS/obtenerUgelDeUsuarioResponse")]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioResponse> obtenerUgelDeUsuarioAsync(AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerIEDeUsuario", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerIEDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDirector;
        
        public obtenerIEDeUsuarioRequest() {
        }
        
        public obtenerIEDeUsuarioRequest(int idDirector) {
            this.idDirector = idDirector;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerIEDeUsuarioResponse", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerIEDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public obtenerIEDeUsuarioResponse() {
        }
        
        public obtenerIEDeUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string contrasenaField;
        
        private director directorField;
        
        private int idUsuarioField;
        
        private tipoUsuario tipoUsuarioField;
        
        private bool tipoUsuarioFieldSpecified;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public director director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
                this.RaisePropertyChanged("director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoUsuario tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioSpecified {
            get {
                return this.tipoUsuarioFieldSpecified;
            }
            set {
                this.tipoUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/")]
    public partial class director : persona {
        
        private bool activoField;
        
        private string emailField;
        
        private System.DateTime fechaNombramientoField;
        
        private bool fechaNombramientoFieldSpecified;
        
        private string tipoContratoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaNombramiento {
            get {
                return this.fechaNombramientoField;
            }
            set {
                this.fechaNombramientoField = value;
                this.RaisePropertyChanged("fechaNombramiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNombramientoSpecified {
            get {
                return this.fechaNombramientoFieldSpecified;
            }
            set {
                this.fechaNombramientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNombramientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoContrato {
            get {
                return this.tipoContratoField;
            }
            set {
                this.tipoContratoField = value;
                this.RaisePropertyChanged("tipoContrato");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(director))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idPersonaField;
        
        private string lenguaField;
        
        private string nombresField;
        
        private string religionField;
        
        private ushort sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string lengua {
            get {
                return this.lenguaField;
            }
            set {
                this.lenguaField = value;
                this.RaisePropertyChanged("lengua");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
                this.RaisePropertyChanged("religion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        DIRECTOR_IE,
        
        /// <remarks/>
        DIRECTOR_UGEL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarUsuario", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmorYPazBackend.ServicioUser.usuario usuario;
        
        public verificarUsuarioRequest() {
        }
        
        public verificarUsuarioRequest(AmorYPazBackend.ServicioUser.usuario usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarUsuarioResponse", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class verificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmorYPazBackend.ServicioUser.usuario @return;
        
        public verificarUsuarioResponse() {
        }
        
        public verificarUsuarioResponse(AmorYPazBackend.ServicioUser.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoUsuario", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public obtenerTipoUsuarioRequest() {
        }
        
        public obtenerTipoUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoUsuarioResponse", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public obtenerTipoUsuarioResponse() {
        }
        
        public obtenerTipoUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUgelDeUsuario", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUgelDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreCuentaUsuario;
        
        public obtenerUgelDeUsuarioRequest() {
        }
        
        public obtenerUgelDeUsuarioRequest(string nombreCuentaUsuario) {
            this.nombreCuentaUsuario = nombreCuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUgelDeUsuarioResponse", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUgelDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public obtenerUgelDeUsuarioResponse() {
        }
        
        public obtenerUgelDeUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : AmorYPazBackend.ServicioUser.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<AmorYPazBackend.ServicioUser.UsuarioWS>, AmorYPazBackend.ServicioUser.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioResponse AmorYPazBackend.ServicioUser.UsuarioWS.obtenerIEDeUsuario(AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest request) {
            return base.Channel.obtenerIEDeUsuario(request);
        }
        
        public int obtenerIEDeUsuario(int idDirector) {
            AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest();
            inValue.idDirector = idDirector;
            AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioResponse retVal = ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).obtenerIEDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioResponse> AmorYPazBackend.ServicioUser.UsuarioWS.obtenerIEDeUsuarioAsync(AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest request) {
            return base.Channel.obtenerIEDeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioResponse> obtenerIEDeUsuarioAsync(int idDirector) {
            AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.obtenerIEDeUsuarioRequest();
            inValue.idDirector = idDirector;
            return ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).obtenerIEDeUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmorYPazBackend.ServicioUser.verificarUsuarioResponse AmorYPazBackend.ServicioUser.UsuarioWS.verificarUsuario(AmorYPazBackend.ServicioUser.verificarUsuarioRequest request) {
            return base.Channel.verificarUsuario(request);
        }
        
        public AmorYPazBackend.ServicioUser.usuario verificarUsuario(AmorYPazBackend.ServicioUser.usuario usuario) {
            AmorYPazBackend.ServicioUser.verificarUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.verificarUsuarioRequest();
            inValue.usuario = usuario;
            AmorYPazBackend.ServicioUser.verificarUsuarioResponse retVal = ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).verificarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.verificarUsuarioResponse> AmorYPazBackend.ServicioUser.UsuarioWS.verificarUsuarioAsync(AmorYPazBackend.ServicioUser.verificarUsuarioRequest request) {
            return base.Channel.verificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.verificarUsuarioResponse> verificarUsuarioAsync(AmorYPazBackend.ServicioUser.usuario usuario) {
            AmorYPazBackend.ServicioUser.verificarUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.verificarUsuarioRequest();
            inValue.usuario = usuario;
            return ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).verificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmorYPazBackend.ServicioUser.obtenerTipoUsuarioResponse AmorYPazBackend.ServicioUser.UsuarioWS.obtenerTipoUsuario(AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest request) {
            return base.Channel.obtenerTipoUsuario(request);
        }
        
        public string obtenerTipoUsuario(int idUsuario) {
            AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest();
            inValue.idUsuario = idUsuario;
            AmorYPazBackend.ServicioUser.obtenerTipoUsuarioResponse retVal = ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).obtenerTipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerTipoUsuarioResponse> AmorYPazBackend.ServicioUser.UsuarioWS.obtenerTipoUsuarioAsync(AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest request) {
            return base.Channel.obtenerTipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerTipoUsuarioResponse> obtenerTipoUsuarioAsync(int idUsuario) {
            AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.obtenerTipoUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).obtenerTipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioResponse AmorYPazBackend.ServicioUser.UsuarioWS.obtenerUgelDeUsuario(AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest request) {
            return base.Channel.obtenerUgelDeUsuario(request);
        }
        
        public int obtenerUgelDeUsuario(string nombreCuentaUsuario) {
            AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest();
            inValue.nombreCuentaUsuario = nombreCuentaUsuario;
            AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioResponse retVal = ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).obtenerUgelDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioResponse> AmorYPazBackend.ServicioUser.UsuarioWS.obtenerUgelDeUsuarioAsync(AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest request) {
            return base.Channel.obtenerUgelDeUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioResponse> obtenerUgelDeUsuarioAsync(string nombreCuentaUsuario) {
            AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest inValue = new AmorYPazBackend.ServicioUser.obtenerUgelDeUsuarioRequest();
            inValue.nombreCuentaUsuario = nombreCuentaUsuario;
            return ((AmorYPazBackend.ServicioUser.UsuarioWS)(this)).obtenerUgelDeUsuarioAsync(inValue);
        }
    }
}
