//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmorYPazBackend.servicioDirectorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", ConfigurationName="servicioDirectorWS.DirectorWS")]
    public interface DirectorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/DirectorWS/listarDirectoresTodasRequest" +
            "", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/DirectorWS/listarDirectoresTodasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasResponse listarDirectoresTodas(AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rrhh.softprog.pucp.edu.pe/DirectorWS/listarDirectoresTodasRequest" +
            "", ReplyAction="http://services.rrhh.softprog.pucp.edu.pe/DirectorWS/listarDirectoresTodasRespons" +
            "e")]
        System.Threading.Tasks.Task<AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasResponse> listarDirectoresTodasAsync(AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/")]
    public partial class director : persona {
        
        private bool activoField;
        
        private string emailField;
        
        private System.DateTime fechaNombramientoField;
        
        private bool fechaNombramientoFieldSpecified;
        
        private string tipoContratoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaNombramiento {
            get {
                return this.fechaNombramientoField;
            }
            set {
                this.fechaNombramientoField = value;
                this.RaisePropertyChanged("fechaNombramiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNombramientoSpecified {
            get {
                return this.fechaNombramientoFieldSpecified;
            }
            set {
                this.fechaNombramientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNombramientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoContrato {
            get {
                return this.tipoContratoField;
            }
            set {
                this.tipoContratoField = value;
                this.RaisePropertyChanged("tipoContrato");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(director))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string direccionField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idPersonaField;
        
        private string lenguaField;
        
        private string nombresField;
        
        private string religionField;
        
        private ushort sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string lengua {
            get {
                return this.lenguaField;
            }
            set {
                this.lenguaField = value;
                this.RaisePropertyChanged("lengua");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string religion {
            get {
                return this.religionField;
            }
            set {
                this.religionField = value;
                this.RaisePropertyChanged("religion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDirectoresTodas", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDirectoresTodasRequest {
        
        public listarDirectoresTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDirectoresTodasResponse", WrapperNamespace="http://services.rrhh.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDirectoresTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rrhh.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AmorYPazBackend.servicioDirectorWS.director[] @return;
        
        public listarDirectoresTodasResponse() {
        }
        
        public listarDirectoresTodasResponse(AmorYPazBackend.servicioDirectorWS.director[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DirectorWSChannel : AmorYPazBackend.servicioDirectorWS.DirectorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DirectorWSClient : System.ServiceModel.ClientBase<AmorYPazBackend.servicioDirectorWS.DirectorWS>, AmorYPazBackend.servicioDirectorWS.DirectorWS {
        
        public DirectorWSClient() {
        }
        
        public DirectorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DirectorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DirectorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasResponse AmorYPazBackend.servicioDirectorWS.DirectorWS.listarDirectoresTodas(AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest request) {
            return base.Channel.listarDirectoresTodas(request);
        }
        
        public AmorYPazBackend.servicioDirectorWS.director[] listarDirectoresTodas() {
            AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest inValue = new AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest();
            AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasResponse retVal = ((AmorYPazBackend.servicioDirectorWS.DirectorWS)(this)).listarDirectoresTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasResponse> AmorYPazBackend.servicioDirectorWS.DirectorWS.listarDirectoresTodasAsync(AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest request) {
            return base.Channel.listarDirectoresTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasResponse> listarDirectoresTodasAsync() {
            AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest inValue = new AmorYPazBackend.servicioDirectorWS.listarDirectoresTodasRequest();
            return ((AmorYPazBackend.servicioDirectorWS.DirectorWS)(this)).listarDirectoresTodasAsync(inValue);
        }
    }
}
